import type { Metadata } from "next";
import { Nav } from "@/components/nav";
import { RouteTransition } from "@/components/route-transition";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className="flex min-h-screen flex-col overflow-x-hidden bg-background">
        <Nav />
        <RouteTransition>{children}</RouteTransition>
      </body>
    </html>
  );
}
